#ifndef TASK_TAGS_H_INCLUDED
#define TASK_TAGS_H_INCLUDED

// "Tags" are assigned to each task inside uPCN to make tracing in embedded
// environments easier.

enum upcn_task_tags {
	IDLE_TASK_TAG = 0,
	CONTACT_RX_TASK_TAG,
	ROUTER_TASK_TAG,
	BUNDLE_PROCESSOR_TASK_TAG,
	CONTACT_MANAGER_TASK_TAG,
	CONTACT_TX_TASK_TAG,
	ROUTER_OPTIMIZER_TASK_TAG,
	CLA_SPECIFIC_TASK_TAG,
	FS_TASK_TAG,
	CONFIG_AGENT_TASK_TAG,
	APPLICATION_AGENT_LISTENER_TASK_TAG,
	APPLICATION_AGENT_COMM_TASK_TAG,
};

#endif // TASK_TAGS_H_INCLUDED
